### PR TITLE
.nvmrc: bump node 18

### PR DESCRIPTION
**Pull request by rbuj**
Netlify requires these dependencies on build stage, however they are not in the right place.
```diff
diff --git a/package-lock.json b/package-lock.json
index c27f06b..57ff33f 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -8,11 +8,6 @@
       "name": "uoc-boilerplate",
       "version": "3.9.0",
       "license": "MIT",
-      "dependencies": {
-        "@parcel/watcher-linux-x64-glibc": "*",
-        "@swc/core-linux-x64-gnu": "*",
-        "lightningcss-linux-x64-gnu": "*"
-      },
       "devDependencies": {
         "@parcel/transformer-sass": "^2.12.0",
         "autoprefixer": "^10.4.15",
```
Thus, this PR could move dependencies to optionalDependencies, from package-lock.json to package.json.

Moreover, It bumps the version of node in .nvmrc file to match the current supported version.

### CODE REVIEW

**Comment by jorditarrida** [comment]
Hello @rbuj! Thank you very much for your contribution.

Good catch on the `.nvmrc` version, it should be bumped.

Regarding the main issue in this PR, the three dependencies you list are not listed by default in UOC Boilerplate's `package.json`. They are listed as optional dependencies of some of the packages installed by default (for example, we have `parcel` in the `devDependencies`, which has `@parcel/fs` in the `dependencies`, which in turn has `@parcel/watcher` in the dependencies, which has `@parcel/watcher-linux-x64-glibc` in the `optionalDependencies`). The three dependencies you mention are indeed in the `package-lock.json` because it was generated from a default install (`npm i` which by default installs the `optionalDependencies`).

Is this setup giving you any issues that I might be not aware of? Otherwise, what are any reasons for of including these as `optionalDependencies` in the `package.json`? In my experience you should not encounter any issues when trying to deploy to Netlify as the optionalDependencies are already listed in the package-lock.json, but I might be missing something here.

**Comment by rbuj** [comment]
I got build erros like https://app.netlify.com/sites/beautiful-scone-034d86/deploys/6718dfa44114a4000830be68.

I guess where they came from... I created a package-lock.json from scrath and the package manager didn't take care about the optionalDependencies when populated it. After all I didn't get any issue on my local machine (macOS).

THX

**Comment by jorditarrida** [comment]
Can you confirm then if the default setup (without overwriting the `package-lock.json`) works for you? I could deploy it to Netlify with no issues but I'll wait for your confirmation.

If so, could you remove that commit from your PR? So that I can merge the commit regarding the `.nvmrc` file with the proper attribution :) Once again, thanks for your contribution!

**Comment by rbuj** [comment]
Yes, it worked as expected with your suggestions.
- https://app.netlify.com/sites/beautiful-scone-034d86/deploys/671bc4df16a125000881bbf5

I'm goint to change the pull request ASAP.

THX

**Comment by rbuj** [comment]
Done. The current version of node 18 is v18.20.4 at the momemt.
```
$ LANG=C date && node --version &> .nvmrc && cat .nvmrc 
Fri Oct 25 18:31:19 CEST 2024
v18.20.4
```
Feel free to apply any change to the PR / commit.

THX

**Pull request merged**
